services:
  - type: web
    name: jiosaavn-jam
    runtime: node
    buildCommand: bun install && bun run build
    startCommand: s
    envVars:
      - key: NODE_ENV
        value: production
